consume graphql-voyager via yarn instead of git submodule
threatgrid/ring-graphql-voyager pull request #1
Opened 2020-06-04 15:53 UTC by viebel

2020-06-04 15:54 UTC, viebel commented
Please merge into master and deploy a new version of `ring-graphql-voyager` that will consume latest `graphql-voyager`

2020-06-04 23:43 UTC, vemv requested changes
Generally git is safer than any package manager at all, since it's immutable / content-adressed.

Why not just update the SHA the submodule is pointing at?

That sort of reasoning would be great to share in advance as an issue, as opposed to a PR that introduces more moving parts (NPM, an usual suspect in security) and various hard-to-review blobs (yarn.lock, which may theoretically sneak vulnerable dependencies).

Finally, you may want to look into https://www.webjars.org/ . Currently it doesn't host graphql-voyager but it may be a welcome contribution.

2020-06-04 23:43 UTC, vemv commented on package.json
> +  "repository": "git@github.com:viebel/ring-graphql-voyager.git",
These 3 LOCs are spurious

2020-06-05 13:48 UTC, viebel commented
I tried and I was confused by the fact that `npm run build:release` reports a failure.
In fact, the files were generated under the dist folder. 
updated the PR

2020-06-05 13:59 UTC, vemv approved these changes
Kudos for the amend!

2020-06-05 14:02 UTC, msprunck approved these changes
LGTM!

2020-06-05 14:23 UTC, merged

2020-06-05 14:48 UTC, viebel commented
Could you deploy a new version of the `ring-graphql-voyager` and of `ring-graphql-ui` soon?

2020-06-05 14:52 UTC, msprunck commented
> Could you deploy a new version of the `ring-graphql-voyager` and of `ring-graphql-ui` soon?

Yes will try to do it today